# Example Docker Compose File

version: "3.8"

# All services will be in same network
services:
  mongo:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gaurav98094
      - MONGO_INITDB_ROOT_PASSWORD=secret
    container_name: mongodb
    # env_file:
    #   - ./env/mongo.env
  backend:
    build: './backend'
    # build: 
    #   - context: ./backend
    #   - dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gaurav98094
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - logs:/app/logs
      - ./backend/:/app
      - /app/node_modules
    ports:
      - '80:80'
    depends_on:
      - mongo
  frontend:
    build: './frontend'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - mongo
      - backend

# Any named volumes has to be listed here (only named volumes)
volumes:
  - data
  - logs


# docker-compose up
# docker-compose down -v